### ISSUE TITLE
Change imports from nebril/helm to k8s.io/helm

### ISSUE THREAD

**Issue by nebril** [helm/rudder-appcontroller#4]
When https://github.com/kubernetes/helm/pull/2079 is merged, we need to use helm master libraries instead of my fork.

**Comment by dshulyak** [comment]
I think there is a way in glide to use original import path but change the source. I will take a look tomorrow

**Comment by nebril** [comment]
@dshulyak that would be great, but as rudder is merged in we can just change dependency from nebril/helm to k8s.io/helm . But it would be great if that mechanism worked, it might come useful in the future.
